version: "0.2"
words:
  - adafruit
  - armv
  - binstall
  - bndy
  - Boolish
  - clippy
  - cooldown
  - endfor
  - endgroup
  - endmacro
  - Falsey
  - flate
  - FQBN
  - gnueabi
  - gnueabihf
  - msvc
  - nextest
  - nushell
  - pipx
  - pwsh
  - reqwest
  - rsplit
  - rustup
  - saphyr
  - serde
  - startswith
  - thiserror
  - tlsv
  - topo
  - zizmor
ignorePaths:
  - .gitattributes
  - .gitignore
  - tests/**/*.{json,txt}
  - CHANGELOG.md
